pub mod cli;
pub mod config;
pub mod constants;
pub mod error;
pub mod index;
pub mod ingestion;
pub mod paths;
pub mod pdf;
pub mod pipeline;
pub mod services;
pub mod text;
pub use zetesis_server as server;
